name: pr-builder
run-name: PR Builder
on: pull_request

permissions: read-all
jobs:      
  static-analysis-scanning:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Checkov Scan
      uses: bridgecrewio/checkov-action@v12
      with:
        output_format: cli
        output_file_path: console      
  terraform-plan:
    needs: static-analysis-scanning
    runs-on: ubuntu-latest
     # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@master    

    # Configure AWS Credentials to deploy terraform changes onto AWS
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-west-2
        # This is an assumed role created for GitHub Actions to access the statefile of this terraform project
        role-to-assume: arn:aws:iam::295919900413:role/iac-s3-example-role
        role-session-name: S3IaCExampleRole

    # Terraform Cloud Authentication
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.2
        terraform_wrapper: false
    
    - name: Terraform Format
      run: terraform fmt -check
    
    - name: Terraform Init
      run: terraform init
    
    - name: Terraform Plan
      run: terraform plan -out=tfplan
      continue-on-error: true
    
    - name: Upload TF Plan  
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: tfplan